name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Print Go version and environment
        run: |
          go version
          go env

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v

      - name: Test
        run: bob
